### ISSUE TITLE
Most 3D boxes are correct, but some are shift from their correct position in a frame.

### ISSUE THREAD

**Issue by zeyu-hello** [waymo-research/waymo-open-dataset#75] opened 2019-11-25 07:43 UTC
I use [https://github.com/gdlg/simple-waymo-open-dataset-reader/blob/master/simple_waymo_open_dataset_reader/utils.py](https://github.com/gdlg/simple-waymo-open-dataset-reader/blob/master/simple_waymo_open_dataset_reader/utils.py) function `get, parse_range_image_and_camera_projection, project_to_pointcloud`. Here is my script:
```
dataset = tf.data.TFRecordDataset(tf_file)
for id, data in enumerate(dataset):
     frame = open_dataset.Frame()
     frame.ParseFromString(bytearray(data.numpy()))
     # Get the top laser information
     laser_name = open_dataset.LaserName.TOP
     laser = get(frame.lasers, laser_name)
     laser_calibration = get(frame.context.laser_calibrations, laser_name)

     (range_image, camera_projection, range_image_top_pose) = parse_range_image_and_camera_projection(laser)
     points, cp_points = project_to_pointcloud(frame, range_image, camera_projection,
                                                  range_image_top_pose, laser_calibration)

    box_list = []
    for l, label in enumerate(frame.laser_labels):
        box = [label.box.center_x,
                   label.box.center_y,
                   label.box.center_z,
                   label.box.length,
                   label.box.width,
                   label.box.height,
                   label.box.heading,
                   box_cls]
         box_list.append(box)

```
![image](https://user-images.githubusercontent.com/29373801/69521477-0a469700-0f9a-11ea-8555-5f7936641321.png)

As results, this makes some object point cloud live outside of the bboxes.

**Comment by nan0755** [comment] 2019-11-25 07:59
Another example as below, you can find most boxes are correct bot some may shift a little from its coorect place.
![image](https://user-images.githubusercontent.com/29373801/69522515-89d56580-0f9c-11ea-8668-8483ed8e1568.png)

**Comment by peisun1115** [comment] 2019-11-25 17:26
Thanks for reporting this issue, what is filename of the  2nd example?

**Comment by peisun1115** [comment] 2019-11-25 17:30
It looks like that your code did not take pixel pose into account? Are you able to call our code directly and check whether it produces the same result?

**Comment by nan0755** [comment] 2019-11-26 02:15
pixel pos means the camera pos?

**Comment by peisun1115** [comment] 2019-11-26 02:16
the range image pixel pose

https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto#L217

**Comment by nan0755** [comment] 2019-11-26 02:27
What does `range_image_top_pose` in `(range_image, camera_projection, range_image_top_pose) = parse_range_image_and_camera_projection(laser)` refer?

**Comment by peisun1115** [comment] 2019-11-26 02:29
See the documentation in the code. https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto#L217

**Comment by peisun1115** [comment] 2019-11-26 03:16
You had this comment in your code. https://github.com/gdlg/simple-waymo-open-dataset-reader/blob/master/simple_waymo_open_dataset_reader/utils.py#L306-L312

We use it here
https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/utils/range_image_utils.py#L362-L383

It will be useful if you just compare it with the result of directly calling our function. If you still sees the error, i can take a look at our raw data to see whether this is labeling error or not

**Comment by maowy918** [comment] 2020-03-17 07:54
![image](https://user-images.githubusercontent.com/62279058/76833636-a99fda80-6866-11ea-8b44-e28f2106ff67.png)
@peisun1115 , I see the same error when I use range_image_utils.   It's in 
segment-10500357041547037089_1474_800_1494_800_with_camera_labels.tfrecord
frame number 500. 
And it's not the single frame I get with this problem.

**Comment by maowy918** [comment] 2020-03-17 08:16
![企业微信截图_158443244322](https://user-images.githubusercontent.com/62279058/76835185-80347e00-6869-11ea-9bc4-351309f7caa0.png)
(range_images, camera_projections, range_image_top_pose) = frame_utils.parse_range_image_and_camera_projection(frame)

(range_images, camera_projections, range_image_top_pose) = frame_utils.parse_range_image_and_camera_projection(frame)
      points, cp_points = frame_utils.convert_range_image_to_point_cloud(frame,range_images,camera_projections,range_image_top_pose)
      points=points[0]

      for label in frame.laser_labels:
        x=label.box.center_x
        y=label.box.center_y
        z= label.box.center_z
        l= label.box.length
        w= label.box.width
        h= label.box.height
        r= label.box.heading

This is what I get in another frame.Boxes on the right side seems to be vehicles, but boxes on the mid seems to be wrong, while vehicles on the bottom are not labeled.

**Comment by peisun1115** [comment] 2020-03-17 16:32
This is what i get on from 50 (you said 500, we only have 200 in each scene).

![image](https://user-images.githubusercontent.com/18294241/76878044-7f7ff580-6831-11ea-87ed-89ba63709a27.png) It looks fine to me.

I cannot compare it with your image as your image is a subset. You may also print the label ID so that i can a closer look.

What the filename of the 2nd example? 

It would great if you can put the code in a colab such that i can reproduce. That can make it easier for me to find the problem.

**Comment by maowy918** [comment] 2020-03-18 03:13
![企业微信截图_15844996859249](https://user-images.githubusercontent.com/62279058/76920308-22a23f00-6906-11ea-8e74-1e567d140f37.png)
This is what I get from frame 50，most points and boxes are the same, but I find some miss points in
the mid-left.

![企业微信截图_15845006473718](https://user-images.githubusercontent.com/62279058/76921160-49617500-6908-11ea-9b87-dd1f3c1d952f.png)
And in the centriod, there are two vehicles that are not labeled in the vertical, and overlap with the labeled box, I don't know if it's a mistake.


The upper 2nd example is in the same file in frame 0, and the 1st example is not in the first scene, it may be in the 3rd scene, frame 100

**Comment by peisun1115** [comment] 2020-03-18 03:19
Can you highlight the area in the picture i posted if anything is missing? I need to either have a way to reproduce what you see or have a way to see the error in my visualizer. You may try this https://github.com/waymo-research/waymo-open-dataset/issues/91 visualizer such that both us can see the same thing if it is hard for you to publish your code

**Comment by maowy918** [comment] 2020-03-18 03:26
transfer_type={1:0, 2:1, 3:2, 4:3}
obj_types={0:'Car', 1:'Pedestrian', 2:'Sign', 3:'Cyclist'}
for file in tfs:
    FILENAME = path+file
    dataset = tf.data.TFRecordDataset(FILENAME)
    print(file)
    for data in dataset:
      index="%06d" % num
      frame = open_dataset.Frame()
      frame.ParseFromString(bytearray(data.numpy()))
      (range_images, camera_projections, range_image_top_pose) = frame_utils.parse_range_image_and_camera_projection(frame)
      points, cp_points = frame_utils.convert_range_image_to_point_cloud(frame,range_images,camera_projections,range_image_top_pose)
      points = np.concatenate(points, axis=0)

      object_list = []
      for label in frame.laser_labels:
        if label.type not in transfer_type:
          print(label.type)
          continue
        x=label.box.center_x
        y=label.box.center_y
        z= label.box.center_z
        l= label.box.length/2
        w= label.box.width/2
        h= label.box.height/2
        r= label.box.heading
        obb = np.zeros((8))
        obb[0:3]=np.array([x,y,z])
        obb[3:6]=np.array([l,w,h])
        obb[6]=r
        obb[7]=transfer_type[label.type]
        object_list.append(obb)
      if len(object_list)==0:
        obbs = np.zeros((0,8))
      else:
        obbs = np.vstack(object_list) # (K,8)

      point_num=len(points)
      pc=np.zeros((point_num, 6))
      choose=0
      for i in range(point_num):
        x = points[i][0]
        y = points[i][1]
        z = points[i][2]
        pc[choose][0:3]=np.array([x,y,z])
        choose=choose+1
      
      print(choose)
      pc=pc[0:choose]
      #pc=pc_util.random_sampling(pc, 50000)
      np.savez_compressed(os.path.join(output_folder,'%06d_pc.npz'%(num)),
            pc=pc)

      np.save(os.path.join(output_folder, '%06d_bbox.npy'%(num)), obbs)
      print("frame:"+index, len(points))
      if num%50==0:
        pc_util.write_ply(pc,"%6d_pc.ply"%(num/50))
        pc_util.write_ply(obbs[... , 0:3],"%6d_cen.ply"%(num/50))
        obbs[...,3:6]=obbs[...,3:6]*2
        obbs=obbs[...,0:7]
        pc_util.write_oriented_bbox(obbs, "%6d_box.ply"%(num/50))
      num+=1

This is my code ,I use meshlab as my visualizer

**Comment by peisun1115** [comment] 2020-03-18 03:38
You code only contains the way to parse frame to points and boxes. I cannot use that to reproduce. 

Can you try **one of** the following
1. Find the file and timestamp that you think is problematic. I can decode on my side and publish a figure. You can compare with yours to see whether it is the same or highlight the problematic part on the figure i send.

2.  Use the visulizier i sent above which is accessible to both of us. 

3. Write a colab to reproduce your problem that i can *run* directly.

**Comment by maowy918** [comment] 2020-03-18 06:45
![企业微信截图_15845135123291](https://user-images.githubusercontent.com/62279058/76932877-e501de00-6926-11ea-9be2-e3c751816bf8.png)

I try my best to make my picture look like yours. In frame 50, points in the red box are missing, and I suppose there are two vehicles in the green box that are not labeled.

**Comment by maowy918** [comment] 2020-03-18 07:08
Tensorflow1.14 is already installed in my computer, I don't want to install another tensorflow version.

And I can only get .ply in my code, and then show with meshlab, I don't know how to reproduce on colab.

**Comment by peisun1115** [comment] 2020-03-18 17:03
This 
![image](https://user-images.githubusercontent.com/18294241/76984823-95a6b800-68fc-11ea-84df-1e8cb6cc94ee.png) is what i get for frame 50 (in BEV view as yours). Clearly, boxes are similar but the point cloud is different. Is it possible that you are mixing point cloud and labels from different scenes or timestamps? 

To proceed:
1) Can you dump the frame to a file right after tf record reading?
2) And then dump point cloud and box right after frame decoding?
3) And then dump point cloud and box right before visulization?

**Comment by maowy918** [comment] 2020-03-19 02:45
I don't know how to dump the frame to a file as it's not show in the tutorial.

I dumped point cloud and box right after frame decoding and they are same as the one before visulization.

points, cp_points = frame_utils.convert_range_image_to_point_cloud(frame,range_images,camera_projections,range_image_top_pose)
points = np.concatenate(points, axis=0)
I wonder if this is the right way to parse points

**Comment by peisun1115** [comment] 2020-03-19 03:10
Can you attach those dumped data?

It is important to see the raw frame you read. Can you dump it like this:

frame_str = frame. SerializeToString()

f = open('frame.bin', 'wb')
f.write(frame_str)
f.close()

Then attach this frame.bin

**Comment by maowy918** [comment] 2020-03-19 03:19
[frame.zip](https://github.com/waymo-research/waymo-open-dataset/files/4352495/frame.zip)
frame 50 
.bin is not supported, so I upload .zip

**Comment by peisun1115** [comment] 2020-03-19 04:50
This data is correct. I am able to generate the same visulization based on your dumped data. Can you dump the decoded point cloud right and boxes before your viz tool as numpy array such that I can check whether it is in the visulization or in the decoding?

**Comment by peisun1115** [comment] 2020-03-19 04:55
Actually, i think it is because your either rotated your box or point cloud by 90 degree....  If your rotate your point cloud figure, it is the same as my visualization. Here is a figure without boxes which is clearer to compare... I guess you got the axis wrong.

![image](https://user-images.githubusercontent.com/18294241/77032936-18625e00-6963-11ea-8dff-12fe6825df9a.png)

**Comment by maowy918** [comment] 2020-03-19 05:29
[points_box.zip](https://github.com/waymo-research/waymo-open-dataset/files/4352779/points_box.zip)

    x=label.box.center_x
    y=label.box.center_y
    z= label.box.center_z
    l= label.box.length/2
    w= label.box.width/2
    h= label.box.height/2
    r= label.box.heading
    obb = np.zeros((8))
    obb[0:3]=np.array([x,y,z])
    obb[3:6]=np.array([l,w,h])

for i in range(point_num):
   x = points[i][0]
    y = points[i][1]
    z = points[i][2]
    pc[choose][0:3]=np.array([x,y,z])
I think it's the right direction and in the same axis

**Comment by peisun1115** [comment] 2020-03-19 20:41
i loaded your box.bin and it is of shape (156, 3). i don't know how to interpret that. It should be [-1, 7].  Can you re-upload?

it will be great if you can debug on your own a bit to pin point the bug to make sure there is no axis flip esp in your visulizer.

**Comment by maowy918** [comment] 2020-03-20 02:22
[box.zip](https://github.com/waymo-research/waymo-open-dataset/files/4357660/box.zip)

Is there any wrong with points?

**Comment by peisun1115** [comment] 2020-03-20 19:51
The points are incorrect.

It should be a bug in your code. Pls try our codelab directly.  I have tried it with your frame dump with the colab without little code changes. It generates different point from what you have dumped. 

steps are here:
1. open this colab (https://colab.sandbox.google.com/github/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial.ipynb#scrollTo=Ie94goEUe441)
2.   Upload your frame.bin here
![image](https://user-images.githubusercontent.com/18294241/77201218-5a95b780-6aa9-11ea-9567-f6b7e94cba12.png)
3. Run the code.
The only change you need is to read from your uploaded frame. Code is here.

with tf.io.gfile.GFile('/content/frame.bin', 'rb') as f:
  github_frame = f.read()
  github_frame_decoded = open_dataset.Frame()
  github_frame_decoded.ParseFromString(bytearray(github_frame))
  frame = github_frame_decoded

**Comment by maowy918** [comment] 2020-03-22 10:06
[parse.zip](https://github.com/waymo-research/waymo-open-dataset/files/4364994/parse.zip)

Actually, I get the same points as I did.
I cann't find any bug, I think I did as what's told in the document.
Here is my code, you can run in the root directly, with the only change of the input file path.

**Comment by peisun1115** [comment] 2020-03-23 05:22
Thanks for pasting the code. I've ran your code. It worked for me with minor modifications.  
[parse.py.zip](https://github.com/waymo-research/waymo-open-dataset/files/4367317/parse.py.zip)

You can diff with your code. 

The following places are suspicious in your original code:
1. pc_util
2. num % 50 == 0.   

If you still see any problem, pls upload '/tmp/pc_local.bin'.

Note the points you uploaded was in shape [165820, 6]. it should be [165820, 3]. So i used your first 3 channels.

**Comment by maowy918** [comment] 2020-03-23 06:36
[parse.zip](https://github.com/waymo-research/waymo-open-dataset/files/4367514/parse.zip)
I've ran your code, with the only adding of (pc_util.write_ply(points,"50_pc.ply"))，and get the same result as I got before.
I uploaded the 'pc_util' and 'pc_local.bin' in the zip.
If it works well if your system, I wonder if there is any difference between our 'frame_util' or other util files. I checked branch r1.0 from the waymo-open-dataset.

**Comment by maowy918** [comment] 2020-03-23 06:40
[parse.zip](https://github.com/waymo-research/waymo-open-dataset/files/4367514/parse.zip)
I've ran your code, with the only adding of (pc_util.write_ply(points,"50_pc.ply"))，and get the same result as I got before.
I uploaded the 'pc_util' and 'pc_local.bin' in the zip.
If it works well if your system, I wonder if there is any difference between our 'frame_util' or other util files. I checked branch r1.0 from the waymo-open-dataset.

**Comment by peisun1115** [comment] 2020-03-23 07:31
I've just checked the pc_local.bin.npy. The point cloud looks correct to me. So it must be somewhere after this. You can load points in pc_local.bin.npy and compare it with the one you passed to your visualizer. It should be different. Let me know if it is the same.

**Comment by maowy918** [comment] 2020-03-23 08:06
I don't know how to compare .npy file with .ply file.
But in my code, I ran 'pc_util.write_ply(points,"50_pc.ply")' just after 'np.save('/tmp/pc_local.bin', points)', write_ply can be seen in the pc_util, I think they should be same.
![企业微信截图_15845135123291](https://user-images.githubusercontent.com/62279058/77295010-24ae3880-6d20-11ea-8fcc-258b3a64dc4f.png)
I got this from 50_pc.ply.

**Comment by peisun1115** [comment] 2020-03-23 08:07
Just compare the points. Sort them and compute L2 norm.

**Comment by maowy918** [comment] 2020-03-23 08:21
I used pc_util.read_ply and np.load to get points from 50_pc.ply and pc_local.bin.npy, and they are the same.
They are saved from the same variable.

**Comment by peisun1115** [comment] 2020-03-23 19:19
1. The pc_local.bin.npy from your dump is actually different from mine. You can reproduce it in this colab. I have checked in the colab output as well. In the colab, i downloaded your frame.bin and compared the result with your pc_local.bin.npy. it is different.
https://colab.sandbox.google.com/github/peisun1115/waymo-open-dataset/blob/master/tutorial/Copy_of_Waymo_Open_Dataset_Tutorial_(pip).ipynb

2. I also ran your code directly from my local machine. it also worked.

It will be great if you can reproduce the diff in the Google colab machine directly.

**Comment by maowy918** [comment] 2020-03-24 01:33
There is no difference between our parse code.
I think there may be some difference between our downloaded waymo-open-dataset or other files.
Can you offer me a copy of them?

**Comment by peisun1115** [comment] 2020-03-24 01:36
i am not downloading any files. I am using the pre-compiled package.  See the colab above.

**Comment by peisun1115** [comment] 2020-03-24 01:38
Note that you can run the colab directly (read the first cell).

**Comment by maowy918** [comment] 2020-03-24 02:00
I get the same result as shown in the colab.
But where is the difference between my code and code in the colab.
I cann't find any bug in my code.

**Comment by peisun1115** [comment] 2020-03-24 02:02
Maybe try the pre-compiled package? Or even on a fresh cloud machine?

**Comment by maowy918** [comment] 2020-03-24 02:04
Do you get the same result as mine using my code?

**Comment by peisun1115** [comment] 2020-03-24 02:06
No. I do not. I get the same result as what is shown in the colab when using your code without changing anything.

**Comment by maowy918** [comment] 2020-03-24 02:08
Ok, I will try to run in another environment.

**Comment by peisun1115** [comment] 2020-03-24 02:11
To make the experiment more isolated, you can just copy the code from colab and run it locally (in a different environment)  or change your code to read from the frame.bin  you dumped earlier.

**Comment by maowy918** [comment] 2020-03-26 09:15
I found my mistake yesterday，it's really due to my environment error.
I hadn't run pip install waymo-open-dataset, just copied waymo_open_dataset to my root directory and ran to parse tf_record. Program runs without any external mistake, but got the wrong answer. I woder how it could happen.
Things are fine now, and I really appreciate for your help.

**Comment by peisun1115** [comment] 2020-03-26 15:43
Great to see that you have resolved the issue.  Closing for now.

**Closed by peisun1115** 2020-03-26 15:43 UTC
